/** @format */

// @format
const elements = [
  {
    z: 1,
    symbol: "H",
    name: "Hydrogen",
    mass: 1.008,
    config: "1s¹",
    valence: 1,
    period: 1,
    group: "IA",
    type: "nonmetal",
    electronegativity: 2.2,
  },
  {
    z: 2,
    symbol: "He",
    name: "Helium",
    mass: 4.0026,
    config: "1s²",
    valence: 0,
    period: 1,
    group: "VIIIA",
    type: "noble",
    electronegativity: null,
  },
  {
    z: 3,
    symbol: "Li",
    name: "Lithium",
    mass: 6.94,
    config: "[He] 2s¹",
    valence: 1,
    period: 2,
    group: "IA",
    type: "alkali",

    electronegativity: 0.98,
  },
  {
    z: 4,
    symbol: "Be",
    name: "Berylium",
    mass: 9.0122,
    config: "[He] 2s²",
    valence: 2,
    period: 2,
    group: "IIA",
    type: "alkali",

    electronegativity: 1.57,
  },
  {
    z: 5,
    symbol: "B",
    name: "Boron",
    mass: 10.81,
    config: "[He] 2s² 2p¹",
    valence: 3,
    period: 2,
    group: "IIIA",
    type: "metalloid",

    electronegativity: 2.04,
  },
  {
    z: 6,
    symbol: "C",
    name: "Carbon",
    mass: 12.011,
    config: "[He] 2s² 2p²",
    valence: 4,
    period: 2,
    group: "IVA",
    type: "nonmetal",

    electronegativity: 2.55,
  },
  {
    z: 7,
    symbol: "N",
    name: "Nitrogen",
    mass: 14.007,
    config: "[He] 2s² 2p³",
    valence: 5,
    period: 2,
    group: "VA",
    type: "nonmetal",

    electronegativity: 3.04,
  },
  {
    z: 8,
    symbol: "O",
    name: "Oxygen",
    mass: 15.999,
    config: "[He] 2s² 2p⁴",
    valence: 6,
    period: 2,
    group: "VIA",
    type: "nonmetal",

    electronegativity: 3.44,
  },
  {
    z: 9,
    symbol: "F",
    name: "Fluorine",
    mass: 18.998,
    config: "[He] 2s² 2p⁵",
    valence: 7,
    period: 2,
    group: "VIIA",
    type: "nonmetal",

    electronegativity: 3.98,
  },
  {
    z: 10,
    symbol: "Ne",
    name: "Neon",
    mass: 20.18,
    config: "[He] 2s² 2p⁶",
    valence: 0,
    period: 2,
    group: "VIIIA",
    type: "noble",

    electronegativity: null,
  },
  {
    z: 11,
    symbol: "Na",
    name: "Sodium",
    mass: 22.99,
    config: "[Ne] 3s¹",
    valence: 1,
    period: 3,
    group: "IA",
    type: "alkali",

    electronegativity: 0.93,
  },
  {
    z: 12,
    symbol: "Mg",
    name: "Magnesium",
    mass: 24.305,
    config: "[Ne] 3s²",
    valence: 2,
    period: 3,
    group: "IIA",
    type: "alkali",

    electronegativity: 1.31,
  },
  {
    z: 13,
    symbol: "Al",
    name: "Aluminium",
    mass: 26.982,
    config: "[Ne] 3s² 3p¹",
    valence: 3,
    period: 3,
    group: "IIIA",
    type: "alkali",

    electronegativity: 1.61,
  },
  {
    z: 14,
    symbol: "Si",
    name: "Silicium",
    mass: 28.085,
    config: "[Ne] 3s² 3p²",
    valence: 4,
    period: 3,
    group: "IVA",
    type: "metalloid",

    electronegativity: 1.9,
  },
  {
    z: 15,
    symbol: "P",
    name: "Phosphorus",
    mass: 30.974,
    config: "[Ne] 3s² 3p³",
    valence: 5,
    period: 3,
    group: "VA",
    type: "nonmetal",

    electronegativity: 2.19,
  },
  {
    z: 16,
    symbol: "S",
    name: "Sulfur",
    mass: 32.06,
    config: "[Ne] 3s² 3p⁴",
    valence: 6,
    period: 3,
    group: "VIA",
    type: "nonmetal",

    electronegativity: 2.58,
  },
  {
    z: 17,
    symbol: "Cl",
    name: "Chlorine",
    mass: 35.45,
    config: "[Ne] 3s² 3p⁵",
    valence: 7,
    period: 3,
    group: "VIIA",
    type: "nonmetal",

    electronegativity: 3.16,
  },
  {
    z: 18,
    symbol: "Ar",
    name: "Argon",
    mass: 39.948,
    config: "[Ne] 3s² 3p⁶",
    valence: 0,
    period: 3,
    group: "VIIIA",
    type: "noble",

    electronegativity: null,
  },
  {
    z: 19,
    symbol: "K",
    name: "Potassium",
    mass: 39.098,
    config: "[Ar] 4s¹",
    valence: 1,
    period: 4,
    group: "IA",
    type: "alkali",

    electronegativity: 0.82,
  },
  {
    z: 20,
    symbol: "Ca",
    name: "Calcium",
    mass: 40.078,
    config: "[Ar] 4s²",
    valence: 2,
    period: 4,
    group: "IIA",
    type: "alkali",

    electronegativity: 1.0,
  },
  {
    z: 21,
    symbol: "Sc",
    name: "Scandium",
    mass: 44.956,
    config: "[Ar] 3d¹ 4s²",
    valence: 3,
    period: 4,
    group: "IIIB",
    type: "transition",

    electronegativity: 1.36,
  },
  {
    z: 22,
    symbol: "Ti",
    name: "Titanium",
    mass: 47.867,
    config: "[Ar] 3d² 4s²",
    valence: 4,
    period: 4,
    group: "IVB",
    type: "transition",

    electronegativity: 1.54,
  },
  {
    z: 23,
    symbol: "V",
    name: "Vanadium",
    mass: 50.942,
    config: "[Ar] 3d³ 4s²",
    valence: 5,
    period: 4,
    group: "VB",
    type: "transition",

    electronegativity: 1.63,
  },
  {
    z: 24,
    symbol: "Cr",
    name: "Chromium",
    mass: 51.996,
    config: "[Ar] 3d⁵ 4s¹",
    valence: 6,
    period: 4,
    group: "VIB",
    type: "transition",

    electronegativity: 1.66,
  },
  {
    z: 25,
    symbol: "Mn",
    name: "Manganese",
    mass: 54.938,
    config: "[Ar] 3d⁵ 4s²",
    valence: 7,
    period: 4,
    group: "VIIB",
    type: "transition",

    electronegativity: 1.55,
  },
  {
    z: 26,
    symbol: "Fe",
    name: "Iron",
    mass: 55.845,
    config: "[Ar] 3d⁶ 4s²",
    valence: 3,
    period: 4,
    group: "VIIIB",
    type: "transition",

    electronegativity: 1.83,
  },
  {
    z: 27,
    symbol: "Co",
    name: "Cobalt",
    mass: 58.933,
    config: "[Ar] 3d⁷ 4s²",
    valence: 2,
    period: 4,
    group: "VIIIB",
    type: "transition",

    electronegativity: 1.88,
  },
  {
    z: 28,
    symbol: "Ni",
    name: "Nickel",
    mass: 58.693,
    config: "[Ar] 3d⁸ 4s²",
    valence: 2,
    period: 4,
    group: "VIIIB",
    type: "transition",

    electronegativity: 1.91,
  },
  {
    z: 29,
    symbol: "Cu",
    name: "Copper",
    mass: 63.546,
    config: "[Ar] 3d¹⁰ 4s¹",
    valence: 2,
    period: 4,
    group: "IB",
    type: "transition",

    electronegativity: 1.9,
  },
  {
    z: 30,
    symbol: "Zn",
    name: "Zinc",
    mass: 65.38,
    config: "[Ar] 3d¹⁰ 4s²",
    valence: 2,
    period: 4,
    group: "IIB",
    type: "transition",

    electronegativity: 1.65,
  },
  {
    z: 31,
    symbol: "Ga",
    name: "Gallium",
    mass: 69.723,
    config: "[Ar] 3d¹⁰ 4s² 4p¹",
    valence: 3,
    period: 4,
    group: "IIIA",
    type: "alkali",

    electronegativity: 1.81,
  },
  {
    z: 32,
    symbol: "Ge",
    name: "Germanium",
    mass: 72.63,
    config: "[Ar] 3d¹⁰ 4s² 4p²",
    valence: 4,
    period: 4,
    group: "IVA",
    type: "metalloid",

    electronegativity: 2.01,
  },
  {
    z: 33,
    symbol: "As",
    name: "Arsenic",
    mass: 74.922,
    config: "[Ar] 3d¹⁰ 4s² 4p³",
    valence: 5,
    period: 4,
    group: "VA",
    type: "metalloid",

    electronegativity: 2.18,
  },
  {
    z: 34,
    symbol: "Se",
    name: "Selenium",
    mass: 78.971,
    config: "[Ar] 3d¹⁰ 4s² 4p⁴",
    valence: 6,
    period: 4,
    group: "VIA",
    type: "nonmetal",

    electronegativity: 2.55,
  },
  {
    z: 35,
    symbol: "Br",
    name: "Bromine",
    mass: 79.904,
    config: "[Ar] 3d¹⁰ 4s² 4p⁵",
    valence: 7,
    period: 4,
    group: "VIIA",
    type: "nonmetal",

    electronegativity: 2.96,
  },
  {
    z: 36,
    symbol: "Kr",
    name: "Krypton",
    mass: 83.798,
    config: "[Ar] 3d¹⁰ 4s² 4p⁶",
    valence: 0,
    period: 4,
    group: "VIIIA",
    type: "noble",

    electronegativity: 3.0,
  },
  {
    z: 37,
    symbol: "Rb",
    name: "Rubidium",
    mass: 85.468,
    config: "[Kr] 5s¹",
    valence: 1,
    period: 5,
    group: "IA",
    type: "alkali",

    electronegativity: 0.82,
  },
  {
    z: 38,
    symbol: "Sr",
    name: "Strontium",
    mass: 87.62,
    config: "[Kr] 5s²",
    valence: 2,
    period: 5,
    group: "IIA",
    type: "alkali",

    electronegativity: 0.95,
  },
  {
    z: 39,
    symbol: "Y",
    name: "Yttrium",
    mass: 88.906,
    config: "[Kr] 4d¹ 5s²",
    valence: 3,
    period: 5,
    group: "IIIB",
    type: "transition",

    electronegativity: 1.22,
  },
  {
    z: 40,
    symbol: "Zr",
    name: "Zirconium",
    mass: 91.224,
    config: "[Kr] 4d² 5s²",
    valence: 4,
    period: 5,
    group: "IVB",
    type: "transition",

    electronegativity: 1.33,
  },
  {
    z: 41,
    symbol: "Nb",
    name: "Niobium",
    mass: 92.906,
    config: "[Kr] 4d⁴ 5s¹",
    valence: 5,
    period: 5,
    group: "VB",
    type: "transition",

    electronegativity: 1.6,
  },
  {
    z: 42,
    symbol: "Mo",
    name: "Molybdenum",
    mass: 95.95,
    config: "[Kr] 4d⁵ 5s¹",
    valence: 6,
    period: 5,
    group: "VIB",
    type: "transition",

    electronegativity: 2.16,
  },
  {
    z: 43,
    symbol: "Tc",
    name: "Technetium",
    mass: 97,
    config: "[Kr] 4d⁵ 5s²",
    valence: 7,
    period: 5,
    group: "VIIB",
    type: "transition",

    electronegativity: 1.9,
  },
  {
    z: 44,
    symbol: "Ru",
    name: "Ruthenium",
    mass: 101.07,
    config: "[Kr] 4d⁷ 5s¹",
    valence: 3,
    period: 5,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.2,
  },
  {
    z: 45,
    symbol: "Rh",
    name: "Rhodium",
    mass: 102.91,
    config: "[Kr] 4d⁸ 5s¹",
    valence: 3,
    period: 5,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.28,
  },
  {
    z: 46,
    symbol: "Pd",
    name: "Palladium",
    mass: 106.42,
    config: "[Kr] 4d¹⁰",
    valence: 2,
    period: 5,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.2,
  },
  {
    z: 47,
    symbol: "Ag",
    name: "Silver",
    mass: 107.87,
    config: "[Kr] 4d¹⁰ 5s¹",
    valence: 1,
    period: 5,
    group: "IB",
    type: "transition",

    electronegativity: 1.93,
  },
  {
    z: 48,
    symbol: "Cd",
    name: "Cadmium",
    mass: 112.41,
    config: "[Kr] 4d¹⁰ 5s²",
    valence: 2,
    period: 5,
    group: "IIB",
    type: "transition",

    electronegativity: 1.69,
  },
  {
    z: 49,
    symbol: "In",
    name: "Indium",
    mass: 114.82,
    config: "[Kr] 4d¹⁰ 5s² 5p¹",
    valence: 3,
    period: 5,
    group: "IIIA",
    type: "alkali",

    electronegativity: 1.78,
  },
  {
    z: 50,
    symbol: "Sn",
    name: "Tin",
    mass: 118.71,
    config: "[Kr] 4d¹⁰ 5s² 5p²",
    valence: 4,
    period: 5,
    group: "IVA",
    type: "alkali",

    electronegativity: 1.96,
  },
  {
    z: 51,
    symbol: "Sb",
    name: "Antimony",
    mass: 121.76,
    config: "[Kr] 4d¹⁰ 5s² 5p³",
    valence: 5,
    period: 5,
    group: "VA",
    type: "metalloid",

    electronegativity: 2.05,
  },
  {
    z: 52,
    symbol: "Te",
    name: "Tellurium",
    mass: 127.6,
    config: "[Kr] 4d¹⁰ 5s² 5p⁴",
    valence: 6,
    period: 5,
    group: "VIA",
    type: "metalloid",

    electronegativity: 2.1,
  },
  {
    z: 53,
    symbol: "I",
    name: "Iodine",
    mass: 126.9,
    config: "[Kr] 4d¹⁰ 5s² 5p⁵",
    valence: 7,
    period: 5,
    group: "VIIA",
    type: "nonmetal",

    electronegativity: 2.66,
  },
  {
    z: 54,
    symbol: "Xe",
    name: "Xenon",
    mass: 131.29,
    config: "[Kr] 4d¹⁰ 5s² 5p⁶",
    valence: 0,
    period: 5,
    group: "VIIIA",
    type: "noble",

    electronegativity: 2.6,
  },
  {
    z: 55,
    symbol: "Cs",
    name: "Cesium",
    mass: 132.91,
    config: "[Xe] 6s¹",
    valence: 1,
    period: 6,
    group: "IA",
    type: "alkali",

    electronegativity: 0.79,
  },
  {
    z: 56,
    symbol: "Ba",
    name: "Barium",
    mass: 137.33,
    config: "[Xe] 6s²",
    valence: 2,
    period: 6,
    group: "IIA",
    type: "alkali",

    electronegativity: 0.89,
  },
  {
    z: 57,
    symbol: "La",
    name: "Lanthanum",
    mass: 138.91,
    config: "[Xe] 5d¹ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.1,
  },
  {
    z: 58,
    symbol: "Ce",
    name: "Cerium",
    mass: 140.12,
    config: "[Xe] 4f¹ 5d¹ 6s²",
    valence: 4,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.12,
  },
  {
    z: 59,
    symbol: "Pr",
    name: "Praseodymium",
    mass: 140.91,
    config: "[Xe] 4f³ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.13,
  },
  {
    z: 60,
    symbol: "Nd",
    name: "Neodymium",
    mass: 144.24,
    config: "[Xe] 4f⁴ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.14,
  },
  {
    z: 61,
    symbol: "Pm",
    name: "Promethium",
    mass: 145,
    config: "[Xe] 4f⁵ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.13,
  },
  {
    z: 62,
    symbol: "Sm",
    name: "Samarium",
    mass: 150.36,
    config: "[Xe] 4f⁶ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.17,
  },
  {
    z: 63,
    symbol: "Eu",
    name: "Europium",
    mass: 151.96,
    config: "[Xe] 4f⁷ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.2,
  },
  {
    z: 64,
    symbol: "Gd",
    name: "Gadolinium",
    mass: 157.25,
    config: "[Xe] 4f⁷ 5d¹ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.2,
  },
  {
    z: 65,
    symbol: "Tb",
    name: "Terbium",
    mass: 158.93,
    config: "[Xe] 4f⁹ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.1,
  },
  {
    z: 66,
    symbol: "Dy",
    name: "Dysprosium",
    mass: 162.5,
    config: "[Xe] 4f¹⁰ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.22,
  },
  {
    z: 67,
    symbol: "Ho",
    name: "Holmium",
    mass: 164.93,
    config: "[Xe] 4f¹¹ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.23,
  },
  {
    z: 68,
    symbol: "Er",
    name: "Erbium",
    mass: 167.26,
    config: "[Xe] 4f¹² 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.24,
  },
  {
    z: 69,
    symbol: "Tm",
    name: "Thulium",
    mass: 168.93,
    config: "[Xe] 4f¹³ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.25,
  },
  {
    z: 70,
    symbol: "Yb",
    name: "Ytterbium",
    mass: 173.04,
    config: "[Xe] 4f¹⁴ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.1,
  },
  {
    z: 71,
    symbol: "Lu",
    name: "Lutetium",
    mass: 174.97,
    config: "[Xe] 4f¹⁴ 5d¹ 6s²",
    valence: 3,
    period: 6,
    group: "IIIB",
    type: "lanthanide",

    electronegativity: 1.27,
  },
  {
    z: 72,
    symbol: "Hf",
    name: "Hafnium",
    mass: 178.49,
    config: "[Xe] 4f¹⁴ 5d² 6s²",
    valence: 4,
    period: 6,
    group: "IVB",
    type: "transition",

    electronegativity: 1.3,
  },
  {
    z: 73,
    symbol: "Ta",
    name: "Tantalum",
    mass: 180.95,
    config: "[Xe] 4f¹⁴ 5d³ 6s²",
    valence: 5,
    period: 6,
    group: "VB",
    type: "transition",

    electronegativity: 1.5,
  },
  {
    z: 74,
    symbol: "W",
    name: "Tungsten",
    mass: 183.84,
    config: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    valence: 6,
    period: 6,
    group: "VIB",
    type: "transition",

    electronegativity: 2.36,
  },
  {
    z: 75,
    symbol: "Re",
    name: "Rhenium",
    mass: 186.21,
    config: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    valence: 7,
    period: 6,
    group: "VIIB",
    type: "transition",

    electronegativity: 1.9,
  },
  {
    z: 76,
    symbol: "Os",
    name: "Osmium",
    mass: 190.23,
    config: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    valence: 4,
    period: 6,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.2,
  },
  {
    z: 77,
    symbol: "Ir",
    name: "Iridium",
    mass: 192.22,
    config: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    valence: 4,
    period: 6,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.2,
  },
  {
    z: 78,
    symbol: "Pt",
    name: "Platinum",
    mass: 195.08,
    config: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    valence: 4,
    period: 6,
    group: "VIIIB",
    type: "transition",

    electronegativity: 2.28,
  },
  {
    z: 79,
    symbol: "Au",
    name: "Gold",
    mass: 196.97,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    valence: 3,
    period: 6,
    group: "IB",
    type: "transition",

    electronegativity: 2.54,
  },
  {
    z: 80,
    symbol: "Hg",
    name: "Mercury",
    mass: 200.59,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    valence: 2,
    period: 6,
    group: "IIB",
    type: "transition",

    electronegativity: 2.0,
  },
  {
    z: 81,
    symbol: "Tl",
    name: "Thallium",
    mass: 204.38,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    valence: 3,
    period: 6,
    group: "IIIA",
    type: "alkali",

    electronegativity: 1.62,
  },
  {
    z: 82,
    symbol: "Pb",
    name: "Lead",
    mass: 207.2,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    valence: 4,
    period: 6,
    group: "IVA",
    type: "alkali",

    electronegativity: 2.33,
  },
  {
    z: 83,
    symbol: "Bi",
    name: "Bismuth",
    mass: 208.98,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    valence: 5,
    period: 6,
    group: "VA",
    type: "alkali",

    electronegativity: 2.02,
  },
  {
    z: 84,
    symbol: "Po",
    name: "Polonium",
    mass: 209,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    valence: 6,
    period: 6,
    group: "VIA",
    type: "metalloid",

    electronegativity: 2.0,
  },
  {
    z: 85,
    symbol: "At",
    name: "Astatine",
    mass: 210,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    valence: 7,
    period: 6,
    group: "VIIA",
    type: "nonmetal",

    electronegativity: 2.2,
  },
  {
    z: 86,
    symbol: "Rn",
    name: "Radon",
    mass: 222,
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    valence: 0,
    period: 6,
    group: "VIIIA",
    type: "noble",

    electronegativity: 2.2,
  },
  {
    z: 87,
    symbol: "Fr",
    name: "Francium",
    mass: 223,
    config: "[Rn] 7s¹",
    valence: 1,
    period: 7,
    group: "IA",
    type: "alkali",

    electronegativity: 0.7,
  },
  {
    z: 88,
    symbol: "Ra",
    name: "Radium",
    mass: 226,
    config: "[Rn] 7s²",
    valence: 2,
    period: 7,
    group: "IIA",
    type: "alkali",

    electronegativity: 0.9,
  },
  {
    z: 89,
    symbol: "Ac",
    name: "Actinium",
    mass: 227,
    config: "[Rn] 6d¹ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.1,
  },
  {
    z: 90,
    symbol: "Th",
    name: "Thorium",
    mass: 232.04,
    config: "[Rn] 6d² 7s²",
    valence: 4,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 91,
    symbol: "Pa",
    name: "Protactinium",
    mass: 231.04,
    config: "[Rn] 5f² 6d¹ 7s²",
    valence: 5,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.5,
  },
  {
    z: 92,
    symbol: "U",
    name: "Uranium",
    mass: 238.03,
    config: "[Rn] 5f³ 6d¹ 7s²",
    valence: 6,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.38,
  },
  {
    z: 93,
    symbol: "Np",
    name: "Neptunium",
    mass: 237,
    config: "[Rn] 5f⁴ 6d¹ 7s²",
    valence: 5,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.36,
  },
  {
    z: 94,
    symbol: "Pu",
    name: "Plutonium",
    mass: 244,
    config: "[Rn] 5f⁶ 7s²",
    valence: 4,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.28,
  },
  {
    z: 95,
    symbol: "Am",
    name: "Americium",
    mass: 243,
    config: "[Rn] 5f⁷ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 96,
    symbol: "Cm",
    name: "Curium",
    mass: 247,
    config: "[Rn] 5f⁷ 6d¹ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 97,
    symbol: "Bk",
    name: "Berkelium",
    mass: 247,
    config: "[Rn] 5f⁹ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 98,
    symbol: "Cf",
    name: "Californium",
    mass: 251,
    config: "[Rn] 5f¹⁰ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 99,
    symbol: "Es",
    name: "Einsteinium",
    mass: 252,
    config: "[Rn] 5f¹¹ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 100,
    symbol: "Fm",
    name: "Fermium",
    mass: 257,
    config: "[Rn] 5f¹² 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 101,
    symbol: "Md",
    name: "Mendelevium",
    mass: 258,
    config: "[Rn] 5f¹³ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 102,
    symbol: "No",
    name: "Nobelium",
    mass: 259,
    config: "[Rn] 5f¹⁴ 7s²",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 103,
    symbol: "Lr",
    name: "Lawrencium",
    mass: 262,
    config: "[Rn] 5f¹⁴ 7s² 7p¹",
    valence: 3,
    period: 7,
    group: "IIIB",
    type: "actinide",

    electronegativity: 1.3,
  },
  {
    z: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    mass: 267,
    config: "[Rn] 5f¹⁴ 6d² 7s²",
    valence: 4,
    period: 7,
    group: "IVB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 105,
    symbol: "Db",
    name: "Dubnium",
    mass: 268,
    config: "[Rn] 5f¹⁴ 6d³ 7s²",
    valence: 5,
    period: 7,
    group: "VB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 106,
    symbol: "Sg",
    name: "Seaborgium",
    mass: 271,
    config: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    valence: 6,
    period: 7,
    group: "VIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 107,
    symbol: "Bh",
    name: "Bohrium",
    mass: 272,
    config: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    valence: 7,
    period: 7,
    group: "VIIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 108,
    symbol: "Hs",
    name: "Hassium",
    mass: 270,
    config: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    valence: 8,
    period: 7,
    group: "VIIIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 109,
    symbol: "Mt",
    name: "Meitnerium",
    mass: 276,
    config: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    valence: 9,
    period: 7,
    group: "VIIIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    mass: 281,
    config: "[Rn] 5f¹⁴ 6d⁹ 7s¹",
    valence: 10,
    period: 7,
    group: "VIIIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 111,
    symbol: "Rg",
    name: "Roentgenium",
    mass: 280,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    valence: 11,
    period: 7,
    group: "IB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 112,
    symbol: "Cn",
    name: "Copernicium",
    mass: 285,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    valence: 2,
    period: 7,
    group: "IIB",
    type: "transition",

    electronegativity: null,
  },
  {
    z: 113,
    symbol: "Nh",
    name: "Nihonium",
    mass: 284,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    valence: 3,
    period: 7,
    group: "IIIA",
    type: "alkali",

    electronegativity: null,
  },
  {
    z: 114,
    symbol: "Fl",
    name: "Flerovium",
    mass: 289,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    valence: 4,
    period: 7,
    group: "IVA",
    type: "alkali",

    electronegativity: null,
  },
  {
    z: 115,
    symbol: "Mc",
    name: "Moscovium",
    mass: 288,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    valence: 5,
    period: 7,
    group: "VA",
    type: "alkali",

    electronegativity: null,
  },
  {
    z: 116,
    symbol: "Lv",
    name: "Livermorium",
    mass: 293,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    valence: 6,
    period: 7,
    group: "VIA",
    type: "alkali",

    electronegativity: null,
  },
  {
    z: 117,
    symbol: "Ts",
    name: "Tennessine",
    mass: 294,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    valence: 7,
    period: 7,
    group: "VIIA",
    type: "alkali",

    electronegativity: null,
  },
  {
    z: 118,
    symbol: "Og",
    name: "Oganesson",
    mass: 294,
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    valence: 0,
    period: 7,
    group: "VIIIA",
    type: "noble",

    electronegativity: null,
  },
];
